#!/bin/bash
set -euo pipefail
clear
echo "Start...."
API_KEY="sk-or-v1-REDACTED"

# ANSI color codes for terminal output
C_RESET=$'\033[0m'
C_BOLD=$'\033[1m'
C_RED=$'\033[31m'
C_GREEN=$'\033[32m'
C_YELLOW=$'\033[33m'
C_BLUE=$'\033[34m'
C_MAGENTA=$'\033[35m'
C_CYAN=$'\033[36m'

# Estimate model strength from its ID and metadata (context length).
# Higher score = stronger model. Uses parameter count from the ID plus
# tier keywords as a heuristic.
model_strength() {
    local id="$1"
    local context_length="${2:-0}"
    local score=0

    # Parameter count from the model ID (e.g. "120b", "550b", "30b").
    local params
    params=$(echo "$id" | grep -oE '[0-9]+b' | head -n1 | tr -d 'b')
    if [[ -n "$params" ]]; then
        score=$((params))
    fi

    # Tier keywords in the name.
    local lower
    lower=$(echo "$id" | tr '[:upper:]' '[:lower:]')
    case "$lower" in
        *ultra*|*super*|*pro*|*max*|*large*|*xl*|*turbo*) score=$((score + 50)) ;;
        *nano*|*mini*|*flash*|*lightning*|*small*|*xs*|*tiny*|*preview*) score=$((score - 30)) ;;
    esac

    # Context length as a secondary signal (larger = stronger).
    if (( context_length >= 100000 )); then
        score=$((score + 20))
    elif (( context_length >= 32000 )); then
        score=$((score + 10))
    fi

    echo "$score"
}

# Minimum model strength to include in the test loop. Models below this are
# skipped to avoid wasting time/resources on weak models.
MIN_MODEL_STRENGTH="${MIN_MODEL_STRENGTH:-70}"

models=()
# models=(
#     "poolside/laguna-xs-2.1:free"
#     "poolside/laguna-s-2.1:free"
#     "cohere/north-mini-code:free"
#     "inclusionai/ling-3.0-flash:free"
#     "openai/gpt-oss-20b:free"
#     # "google/gemma-4-26b-a4b-it:free"
#     # "google/gemma-4-31b-it:free"
#     "nvidia/nemotron-3-super-120b-a12b:free"
#     "nvidia/nemotron-3-ultra-550b-a55b:free"
#     "openrouter/free"
#     "nvidia/nemotron-3-nano-30b-a3b:free"
#     "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free"
# )

# Fetch the full models list once so we can read context_length per model.
# Prefer the live bridge /models endpoint; fall back to the local models.json
# catalog (generated by scripts/fetch_models.py) if the bridge is unreachable.
models_json=$(curl -s -X GET 'http://localhost:11410/v1/models')
if ! echo "$models_json" | jq -e '.data' >/dev/null 2>&1; then
    echo "${C_YELLOW}Bridge /models unreachable; falling back to local models.json catalog${C_RESET}"
    if [[ -f "models.json" ]]; then
        models_json=$(jq '{data: [.models | to_entries[] | {id: .key, context_length: .value.context_length, pricing: {prompt: .value.prompt_price}, supported_parameters: ["tools"], reasoning: {mandatory: false}}]}' models.json)
    else
        echo "${C_RED}No models.json catalog found; cannot determine models.${C_RESET}"
        exit 1
    fi
fi

# Filter to free, tool-capable, non-mandatory-reasoning models.
openrouter_free_models=$(echo "$models_json" | \
  jq -r '.data[] | select((.id | endswith(":free")) and (.pricing.prompt == "0") and ((.supported_parameters // []) | index("tools") != null) and ((.reasoning.mandatory // false) != true)) | .id')

echo "OpenRouter free models: ${openrouter_free_models}"
for model in ${openrouter_free_models}; do
    context_length=$(echo "$models_json" | jq -r --arg id "$model" '.data[] | select(.id == $id) | .context_length // 0')
    strength=$(model_strength "$model" "$context_length")
    if (( strength < MIN_MODEL_STRENGTH )); then
        echo "${C_YELLOW}Skipping weak model: $model (strength=$strength < $MIN_MODEL_STRENGTH)${C_RESET}"
        continue
    fi
    echo "${C_GREEN}Adding model: $model (strength=$strength)${C_RESET}"
    models+=("$model")
done
# exit 0
sleep 5

# loop through the models and run test.sh for each one
for model in "${models[@]}"; do
    echo ""
    echo "---------------------------------------------"
    echo "---------------------------------------------"
    # echo "Testing Open Router model: $model"
    # curl https://openrouter.ai/api/v1/chat/completions   -H "Authorization: Bearer $API_KEY"   -H "Content-Type: application/json"   -d '{
    #     "model": "'$model'",
    #     "messages": [{"role": "user", "content": "Hello!"}]
    # }' | jq
    # echo "---------------------------------------------"
    # continue

    echo "Running test.sh with model: $model"
    MODEL="$model" bash test.sh
    sleep 2
    echo ''
    echo "---------------------------------------------"

    # check if response.md exists and is not empty
    if [[ -s response.md ]]; then
        echo "Response.md exists and is not empty for model: $model"
    else
        echo "Response.md does not exist or is empty for model: $model ====> Skipping PDF generation for model: $model"
        continue
    fi
    echo "Generating PDF report for model: $model"
    bash genpdf.sh
    sleep 2
    echo "PDF report generated for model: $model"
    echo "---------------------------------------------"
done

# "inference_server": {
# "base_url": "https://openrouter.ai/api/v1",
# "api_key": "sk-or-v1-REDACTED"
# },