import asyncio
import os
import re
import time
from typing import Any

from fastapi import HTTPException, Request
from lmos_openai_types import (
    CreateChatCompletionRequest,
    CreateChatCompletionResponse,
    ChatCompletionRequestMessage,
    FinishReason1,
)

from .utils import ToolResultCache, call_tools, chat_completion_add_tools, get_tool_cache, sanitize_tool_result_content
from .genericHttpxClient import get_client
from mcp_bridge.config import config
from mcp_bridge.logging import RequestTraceLogger
from loguru import logger
import json

DEFAULT_MAX_TOOL_TURNS = 12
MIN_MAX_TOOL_TURNS = 12
DEFAULT_TOOL_TIMEOUT_SECONDS = 60
# Number of retries for transient upstream provider errors (HTTP 200 with an
# error body, 429 rate-limit, or 5xx "overloaded"/"unavailable" responses).
# Free-tier providers frequently return these under load; a short retry avoids
# failing a strong model's run on a transient blip.
DEFAULT_UPSTREAM_RETRY_COUNT = 2
DEFAULT_UPSTREAM_RETRY_DELAY_SECONDS = 2.0
# Upper bound on how long we will wait for a provider's `Retry-After` hint.
# Free-tier providers often ask for 60s; we honor it but cap it so a single
# request cannot stall the worker for an unreasonable time.
MAX_UPSTREAM_RETRY_AFTER_SECONDS = 60.0
# Safety cap on the accumulated prompt context (in tokens) for a single
# tool-calling request. Prevents runaway loops where the model keeps issuing
# tool calls and the context grows unboundedly (e.g. 3+ hour requests).
DEFAULT_MAX_CONTEXT_TOKENS = 60000
# Default context window (tokens) assumed for a model when neither the config
# map nor the model-ID heuristic can determine it.
DEFAULT_MODEL_CONTEXT_WINDOW = 128000
# Fraction of the model's context window used as the tool-loop budget. The
# remaining fraction is headroom for the final synthesized answer (and for the
# tool definitions + system prompt already in the prompt).
DEFAULT_CONTEXT_BUDGET_FRACTION = 0.75
# Known model context windows (tokens), used as a fallback when the model ID
# does not carry an explicit context hint and the config map has no entry.
_KNOWN_MODEL_CONTEXT_WINDOWS: dict[str, int] = {
    "nemotron-3-super-120b": 128000,
    "nemotron-3-ultra-550b": 128000,
    "nemotron-3.5-lightning": 128000,
    "minimax-m3": 1000000,
    "dots-3-note-preview": 128000,
}


# Memoization state for the model catalog. The catalog is read once and cached
# in-process, keyed by the file's mtime so a re-run of ``scripts/fetch_models.py``
# (which rewrites ``models.json``) is picked up without a process restart, while
# the hot path (``get_max_context_tokens`` inside the tool loop) never re-reads
# or re-parses the file on every iteration.
_model_catalog_cache: dict[str, int] | None = None
_model_catalog_mtime: float | None = None


def _load_model_catalog() -> dict[str, int]:
    """Load the local ``models.json`` catalog (if present) as a model_id -> context_length map.

    The catalog is generated by ``scripts/fetch_models.py`` from the provider's
    ``/models`` endpoint, so it reflects the real, current context windows
    (which often differ between a model's paid and ``:free`` variants). Returns
    an empty dict if the catalog is missing or unreadable.

    The result is memoized in-process and invalidated only when the file's
    mtime changes, so repeated calls (e.g. once per tool-loop iteration) are
    cheap and do not re-read the file from disk.
    """
    global _model_catalog_cache, _model_catalog_mtime

    catalog_path = os.getenv("MCP_BRIDGE_MODELS_CATALOG", "")
    if not catalog_path:
        catalog_path = os.path.join(os.path.dirname(__file__), "..", "..", "models.json")
    catalog_path = os.path.abspath(catalog_path)

    try:
        mtime = os.path.getmtime(catalog_path)
    except OSError:
        mtime = None

    if _model_catalog_cache is not None and mtime is not None and mtime == _model_catalog_mtime:
        return _model_catalog_cache

    try:
        with open(catalog_path, encoding="utf-8") as fh:
            document = json.load(fh)
        models = document.get("models", {})
        result: dict[str, int] = {}
        for mid, info in models.items():
            ctx = info.get("context_length") if isinstance(info, dict) else None
            if isinstance(ctx, int) and ctx > 0:
                result[mid] = ctx
    except Exception:
        result = {}

    _model_catalog_cache = result
    _model_catalog_mtime = mtime
    return result


def _infer_model_context_window(model_id: str | None) -> int:
    """Best-effort estimate of a model's context window (tokens).

    Resolution order:
      1. The local ``models.json`` catalog (generated from the provider's
         ``/models`` endpoint) — exact model ID match.
      2. Explicit ``model_context_windows`` config map (exact or suffix match).
      3. A context hint embedded in the model ID (e.g. ``128k``, ``1m``, ``200k``).
      4. A known-model lookup by a normalized prefix of the ID.
      5. ``DEFAULT_MODEL_CONTEXT_WINDOW``.
    """
    if not model_id:
        return DEFAULT_MODEL_CONTEXT_WINDOW

    # 1. Local models.json catalog (exact model ID).
    catalog = _load_model_catalog()
    if model_id in catalog:
        return catalog[model_id]

    # 2. Config map (exact match, then suffix match on the last path segment).
    try:
        from mcp_bridge.config import config

        configured = getattr(getattr(config, "inference_server", None), "model_context_windows", None)
        if isinstance(configured, dict):
            if model_id in configured:
                return int(configured[model_id])
            short = model_id.split("/")[-1]
            if short in configured:
                return int(configured[short])
    except Exception:
        pass

    # 3. Context hint embedded in the model ID.
    lowered = model_id.lower()
    # "1m" / "200k" style suffixes (e.g. "model-1m", "model-200k").
    m_match = re.search(r"(\d+)\s*m\b", lowered)
    if m_match:
        return int(m_match.group(1)) * 1_000_000
    k_match = re.search(r"(\d+)\s*(?:k|k\s*tokens?|tokens?)\b", lowered)
    if k_match:
        return int(k_match.group(1)) * 1000

    # 4. Known-model lookup by normalized prefix.
    normalized = re.sub(r"[:/]", "-", lowered).strip("-")
    for known, window in _KNOWN_MODEL_CONTEXT_WINDOWS.items():
        if known in normalized:
            return window

    return DEFAULT_MODEL_CONTEXT_WINDOW


def get_max_context_tokens(model_id: str | None = None) -> int:
    """Return the tool-loop context budget (tokens) for the given model.

    An explicit ``MCP_BRIDGE_MAX_CONTEXT_TOKENS`` environment variable always
    wins (it is a hard override). Otherwise the budget is derived from the
    model's context window scaled by ``MCP_BRIDGE_CONTEXT_BUDGET_FRACTION``
    (default 0.75), so different models get different budgets instead of a
    one-size-fits-all cap.
    """
    raw_value = os.getenv("MCP_BRIDGE_MAX_CONTEXT_TOKENS")
    if raw_value is not None:
        try:
            configured_value = int(raw_value)
        except ValueError:
            logger.warning(
                f"invalid MCP_BRIDGE_MAX_CONTEXT_TOKENS value: {raw_value}; using default {DEFAULT_MAX_CONTEXT_TOKENS}"
            )
            return DEFAULT_MAX_CONTEXT_TOKENS
        if configured_value < 1000:
            logger.warning(
                f"configured MCP_BRIDGE_MAX_CONTEXT_TOKENS={configured_value} is below the safe minimum 1000; using 1000"
            )
            return 1000
        return configured_value

    context_window = _infer_model_context_window(model_id)

    fraction_raw = os.getenv("MCP_BRIDGE_CONTEXT_BUDGET_FRACTION")
    try:
        fraction = float(fraction_raw) if fraction_raw is not None else DEFAULT_CONTEXT_BUDGET_FRACTION
    except ValueError:
        logger.warning(
            f"invalid MCP_BRIDGE_CONTEXT_BUDGET_FRACTION value: {fraction_raw}; using {DEFAULT_CONTEXT_BUDGET_FRACTION}"
        )
        fraction = DEFAULT_CONTEXT_BUDGET_FRACTION

    if not (0.1 <= fraction <= 1.0):
        logger.warning(
            f"MCP_BRIDGE_CONTEXT_BUDGET_FRACTION={fraction} out of range [0.1, 1.0]; using {DEFAULT_CONTEXT_BUDGET_FRACTION}"
        )
        fraction = DEFAULT_CONTEXT_BUDGET_FRACTION

    budget = int(context_window * fraction)
    return max(budget, 1000)


def get_tool_timeout_seconds() -> int:
    raw_value = os.getenv("MCP_BRIDGE_TOOL_TIMEOUT_SECONDS")
    if raw_value is None:
        return DEFAULT_TOOL_TIMEOUT_SECONDS

    try:
        return int(raw_value)
    except ValueError:
        logger.warning(f"invalid MCP_BRIDGE_TOOL_TIMEOUT_SECONDS value: {raw_value}; using default {DEFAULT_TOOL_TIMEOUT_SECONDS}")
        return DEFAULT_TOOL_TIMEOUT_SECONDS


DEFAULT_MAX_STUB_RETRIES = 2


def get_max_stub_retries() -> int:
    raw_value = os.getenv("MCP_BRIDGE_MAX_STUB_RETRIES")
    if raw_value is None:
        return DEFAULT_MAX_STUB_RETRIES

    try:
        configured_value = int(raw_value)
    except ValueError:
        logger.warning(
            f"invalid MCP_BRIDGE_MAX_STUB_RETRIES value: {raw_value}; using default {DEFAULT_MAX_STUB_RETRIES}"
        )
        return DEFAULT_MAX_STUB_RETRIES

    if configured_value < 0:
        logger.warning(f"configured MCP_BRIDGE_MAX_STUB_RETRIES={configured_value} is negative; using 0")
        return 0

    return configured_value


def get_max_tool_turns() -> int:
    raw_value = os.getenv("MCP_BRIDGE_MAX_TOOL_TURNS")
    if raw_value is None:
        return DEFAULT_MAX_TOOL_TURNS

    try:
        configured_value = int(raw_value)
    except ValueError:
        logger.warning(f"invalid MCP_BRIDGE_MAX_TOOL_TURNS value: {raw_value}; using default {DEFAULT_MAX_TOOL_TURNS}")
        return DEFAULT_MAX_TOOL_TURNS

    if configured_value < MIN_MAX_TOOL_TURNS:
        logger.warning(
            f"configured MCP_BRIDGE_MAX_TOOL_TURNS={configured_value} is below the safe minimum {MIN_MAX_TOOL_TURNS}; using {MIN_MAX_TOOL_TURNS}"
        )
        return MIN_MAX_TOOL_TURNS

    return configured_value


def should_continue_tool_loop(
    finish_reason: str | None,
    *,
    tool_call_count: int,
    iteration_count: int,
    max_tool_turns: int = DEFAULT_MAX_TOOL_TURNS,
) -> bool:
    if tool_call_count > 0 and iteration_count < max_tool_turns:
        return True

    if finish_reason in {"stop", "length"}:
        return False

    if finish_reason in {"tool_calls", "function_call"}:
        return tool_call_count > 0 and iteration_count < max_tool_turns

    if tool_call_count <= 0:
        return False

    return iteration_count < max_tool_turns


def _record_timing(trace_logger: RequestTraceLogger | None, stage: str, elapsed_seconds: float) -> None:
    if trace_logger is None:
        return

    trace_logger.record(
        "timing",
        stage=stage,
        elapsed_ms=round(elapsed_seconds * 1000, 2),
    )


def _context_budget_exceeded(
    response: CreateChatCompletionResponse,
    max_context_tokens: int,
) -> bool:
    """Return True if the accumulated prompt context exceeds the budget."""
    usage = getattr(response, "usage", None)
    if usage is None:
        return False
    prompt_tokens = getattr(usage, "prompt_tokens", None)
    if not isinstance(prompt_tokens, int):
        return False
    return prompt_tokens > max_context_tokens


def _context_budget_nearly_exceeded(
    response: CreateChatCompletionResponse,
    max_context_tokens: int,
    threshold: float = 0.7,
) -> bool:
    """Return True if the accumulated prompt context is approaching the budget.

    Used to trigger proactive context compression before the hard limit is hit,
    so the tool loop can keep going instead of stopping early.
    """
    usage = getattr(response, "usage", None)
    if usage is None:
        return False
    prompt_tokens = getattr(usage, "prompt_tokens", None)
    if not isinstance(prompt_tokens, int):
        return False
    return prompt_tokens > (max_context_tokens * threshold)


def _compress_tool_context(
    request_messages: list[ChatCompletionRequestMessage],
    *,
    keep_recent: int = 6,
) -> bool:
    """Compress older tool messages into a single compact summary.

    Long research workflows accumulate many tool messages (search results,
    fetched pages) that bloat the prompt context. When the budget is nearly
    exceeded, this replaces the OLDEST tool messages with a single summarized
    ``role: "tool"`` message, freeing context so the loop can continue.

    Returns True if compression was performed, False otherwise.
    """
    if not request_messages:
        return False

    # Identify tool messages and their indices.
    tool_indices: list[int] = []
    for index, message in enumerate(request_messages):
        role = getattr(getattr(message, "root", message), "role", None)
        if role == "tool":
            tool_indices.append(index)

    if len(tool_indices) <= keep_recent:
        # Not enough tool messages to compress meaningfully.
        return False

    # Keep the most recent `keep_recent` tool messages; compress the older ones.
    compress_indices = tool_indices[:-keep_recent]
    keep_indices = set(tool_indices[-keep_recent:])

    tool_texts: list[str] = []
    for index in compress_indices:
        text = _extract_tool_message_text(request_messages[index])
        if text:
            tool_texts.append(text)

    if not tool_texts:
        return False

    summary = _summarize_tool_messages(tool_texts)
    if not summary:
        return False

    # Build the new message list: drop the compressed tool messages and insert
    # a single summary message in their place.
    #
    # The summary is emitted as a `role: "user"` message (NOT a `role: "tool"`
    # message) because a `tool` message must carry a `tool_call_id` that matches
    # a preceding assistant `tool_calls[].id`. A synthetic id like
    # "context-compression" has no such match, and strict OpenAI-compatible
    # providers reject the request with:
    #   "invalid params, tool result's tool id(context-compression) not found (2013)"
    # A `user` message has no such pairing requirement, so it is protocol-safe.
    new_messages: list[ChatCompletionRequestMessage] = []
    inserted = False
    for index, message in enumerate(request_messages):
        if index in keep_indices:
            new_messages.append(message)
            continue
        if index in compress_indices:
            if not inserted:
                new_messages.append(
                    ChatCompletionRequestMessage.model_validate(
                        {
                            "role": "user",
                            "content": (
                                "[Earlier tool results summarized to save context]\n\n"
                                + summary
                            ),
                        }
                    )
                )
                inserted = True
            continue
        new_messages.append(message)

    # Replace the list in place.
    request_messages[:] = new_messages
    logger.info(
        f"compressed {len(compress_indices)} older tool message(s) into a summary; "
        f"kept {len(keep_indices)} recent tool message(s)"
    )
    return True


def _format_tool_loop_stop_message(*, tool_turns_completed: int, max_tool_turns: int) -> str:
    return f"stopping tool loop after {tool_turns_completed} turn(s); max_tool_turns={max_tool_turns}"


def _normalize_tool_call_key(name: str, arguments: Any) -> str:
    """Build a stable comparison key for a tool call, ignoring whitespace.

    Used to detect when the model re-issues the same tool call across loop
    iterations (a "search loop") instead of converging on an answer.
    """
    arg_text = arguments if isinstance(arguments, str) else json.dumps(arguments, sort_keys=True, ensure_ascii=False)
    return f"{name}::{' '.join(arg_text.split())}"


def _detect_repeated_tool_calls(
    tool_call_items: list[tuple[str, Any]],
    seen_calls: dict[str, int],
    *,
    threshold: int = 3,
) -> bool:
    """Return True if any tool call in this iteration has already been issued
    ``threshold`` or more times across the loop.

    A weak model that keeps re-issuing the same search call without converging
    is a "search loop". Detecting it lets the bridge stop early and synthesize
    a final answer instead of burning tokens and context.

    The threshold is deliberately set above 2 so that a single re-run of a query
    during an otherwise productive research chain (e.g. re-searching a term in a
    different language, or re-running a query to confirm a result) does not kill
    the whole workflow. Only a call issued three or more times is treated as a
    genuine loop. Runaway loops are still bounded by the max-tool-turns and
    context-budget guards.
    """
    repeated = False
    for name, arguments in tool_call_items:
        key = _normalize_tool_call_key(name, arguments)
        seen_calls[key] = seen_calls.get(key, 0) + 1
        if seen_calls[key] >= threshold:
            repeated = True
    return repeated


def _extract_tool_message_text(message: ChatCompletionRequestMessage | Any) -> str | None:
    message_root = getattr(message, "root", message)
    if isinstance(message_root, dict):
        role_value = message_root.get("role")
        content = message_root.get("content")
    else:
        role_value = getattr(getattr(message_root, "role", None), "value", getattr(message_root, "role", None))
        content = getattr(message_root, "content", None)

    if role_value != "tool":
        return None

    if content is None:
        return None

    if hasattr(content, "root"):
        content = content.root

    if isinstance(content, list):
        text_chunks: list[str] = []
        for item in content:
            if isinstance(item, dict):
                text_value = item.get("text")
                if isinstance(text_value, str) and text_value:
                    text_chunks.append(text_value)
            elif hasattr(item, "text"):
                text_value = getattr(item, "text", None)
                if isinstance(text_value, str) and text_value:
                    text_chunks.append(text_value)
            elif hasattr(item, "root") and hasattr(item.root, "text"):
                text_value = getattr(item.root, "text", None)
                if isinstance(text_value, str) and text_value:
                    text_chunks.append(text_value)
        if text_chunks:
            return " ".join(text_chunks[:2])

    if isinstance(content, str):
        return content

    if isinstance(content, dict):
        text_value = content.get("text")
        if isinstance(text_value, str):
            return text_value

    return None


def _normalize_finish_reason(value: str | FinishReason1 | None) -> FinishReason1 | None:
    if value is None:
        return None

    if isinstance(value, FinishReason1):
        return value

    if not isinstance(value, str):
        return None

    normalized = value.strip().lower()
    mapping = {
        "stop": FinishReason1.stop,
        "length": FinishReason1.length,
        "tool_calls": FinishReason1.tool_calls,
        "content_filter": FinishReason1.content_filter,
        "function_call": FinishReason1.function_call,
    }
    return mapping.get(normalized)


def _build_tool_error_response(response: CreateChatCompletionResponse, tool_errors: list[str]) -> CreateChatCompletionResponse:
    error_summary = "; ".join(tool_errors)
    response.choices[0].message.content = (
        "I wasn't able to complete the request because one or more MCP tool calls failed: "
        + error_summary
    )
    response.choices[0].message.tool_calls = None
    response.choices[0].finish_reason = _normalize_finish_reason("stop") or FinishReason1.stop
    return response


def _is_recoverable_tool_error(error: str) -> bool:
    """Return True if a tool error is recoverable by feeding it back to the model.

    Validation errors (e.g. ``sequential-thinking`` rejecting malformed
    arguments) are recoverable — the model can correct its arguments and retry.
    Fatal errors (no client found, unknown tool) are not recoverable by the
    model, so the loop should stop rather than spin.
    """
    if not error:
        return False
    lowered = error.lower()
    fatal_markers = (
        "no mcp client found",
        "unknown tool",
        "tool not found",
        "client not found",
        "not found for tool",
    )
    if any(marker in lowered for marker in fatal_markers):
        return False
    return True


def _should_stop_tool_loop_on_tool_errors(
    tool_errors: list[str],
    request_messages: list[ChatCompletionRequestMessage],
) -> bool:
    if not tool_errors:
        return False

    # Fatal errors (no client / unknown tool) cannot be fixed by the model, so
    # stop immediately regardless of evidence.
    if any(not _is_recoverable_tool_error(error) for error in tool_errors):
        return True

    # Timeout errors with partial evidence are recoverable — the model can
    # continue with what it has. Keep looping even if there are several.
    evidence_text = "\n".join(
        _extract_tool_message_text(message) or ""
        for message in request_messages
        if getattr(getattr(message, "root", message), "role", None) == "tool"
    )
    timeout_error_count = sum(1 for error in tool_errors if "timeout" in error.lower() or "timed out" in error.lower())
    if timeout_error_count and evidence_text.strip():
        return False

    # Recoverable errors (validation, timeout) should be fed back to the model
    # for correction. Only stop if there are too many to avoid an infinite loop.
    if len(tool_errors) > 3:
        return True

    return False


def _build_synthesis_request(
    request: CreateChatCompletionRequest,
    *,
    stop_reason: str,
    request_messages: list[ChatCompletionRequestMessage],
    force_answer: bool = False,
) -> CreateChatCompletionRequest:
    synthesis_request = request.model_copy(deep=True)
    synthesis_request.messages = list(request_messages)
    synthesis_request.tools = []

    if force_answer:
        instruction = (
            "Write the final answer now. Do NOT call any tools and do NOT emit any tool-call "
            "markup. Use only the evidence already present in the conversation to produce a "
            "complete, well-structured answer to the original question. Be concise but thorough."
        )
    else:
        instruction = (
            "Synthesize the information gathered from the tool results into a helpful final answer. "
            "Use the evidence already present in the conversation, be concise but complete, and "
            "avoid mentioning the tool-loop limit unless it is necessary to explain missing information."
        )
    if stop_reason == "max_tool_turns":
        instruction += " The tool workflow stopped early, so if some information is incomplete, say so clearly."
    elif stop_reason == "max_context_tokens":
        instruction += " The tool workflow stopped early because the conversation context grew too large, so if some information is incomplete, say so clearly."
    elif stop_reason == "repeated_tool_calls":
        instruction += " The tool workflow stopped because the same tool call was repeated without new information, so synthesize the best answer from the evidence already gathered."
    elif stop_reason == "unfulfilled_action_stub":
        instruction += " A previous attempt only announced an action (e.g. \"Let me fetch...\") without completing it or calling any tool, so actually answer the question now using whatever information is already available."

    synthesis_request.messages.append(
        ChatCompletionRequestMessage.model_validate(
            {
                "role": "user",
                "content": instruction,
            }
        )
    )
    return synthesis_request


async def _try_synthesize_tool_loop_result(
    client: Any,
    request: CreateChatCompletionRequest,
    *,
    stop_reason: str,
    request_messages: list[ChatCompletionRequestMessage],
) -> CreateChatCompletionResponse | None:
    # First pass: ask the model to synthesize from the gathered evidence. If it
    # returns empty content or tries to call tools again (a common failure when
    # the history is full of tool calls), retry once with a stronger
    # "write the answer now, do not call tools" instruction.
    for attempt, force_answer in enumerate((False, True)):
        synthesis_request = _build_synthesis_request(
            request,
            stop_reason=stop_reason,
            request_messages=request_messages,
            force_answer=force_answer,
        )
        try:
            text = (
                await client.post(
                    "/chat/completions",
                    json=synthesis_request.model_dump(exclude_defaults=True, exclude_none=True, exclude_unset=True),
                )
            ).text
            response = CreateChatCompletionResponse.model_validate_json(text)
            content = getattr(response.choices[0].message, "content", None) if response.choices else None
            if content is None:
                if attempt == 0:
                    continue
                return None
            content_text = str(content)
            # If the synthesis contains pseudo tool-call markers, strip them and
            # keep any real analysis text around them. The synthesis request has no
            # tools, so markers are noise — but the model may have written a real
            # answer around them. Only reject if nothing usable remains.
            if _contains_pseudo_tool_call_markers(content_text):
                content_text = _strip_pseudo_tool_call_markers(content_text)
            if content_text.strip():
                response.choices[0].message.content = content_text
                response.choices[0].message.tool_calls = None
                response.choices[0].finish_reason = _normalize_finish_reason("stop") or FinishReason1.stop
                return response
            # Empty content: retry once with the stronger instruction.
            if attempt == 0:
                continue
        except Exception as exc:
            logger.warning(f"tool loop synthesis request failed: {exc}")
            if attempt == 0:
                continue

    return None


def _extract_message_text(message: ChatCompletionRequestMessage | Any) -> str:
    message_root = getattr(message, "root", message)
    if isinstance(message_root, dict):
        content = message_root.get("content")
    else:
        content = getattr(message_root, "content", None)

    if content is None:
        return ""

    if hasattr(content, "root"):
        content = content.root

    if isinstance(content, str):
        return content

    if isinstance(content, list):
        text_chunks: list[str] = []
        for item in content:
            if isinstance(item, dict):
                text_value = item.get("text")
                if isinstance(text_value, str) and text_value:
                    text_chunks.append(text_value)
            elif hasattr(item, "text"):
                text_value = getattr(item, "text", None)
                if isinstance(text_value, str) and text_value:
                    text_chunks.append(text_value)
            elif hasattr(item, "root") and hasattr(item.root, "text"):
                text_value = getattr(item.root, "text", None)
                if isinstance(text_value, str) and text_value:
                    text_chunks.append(text_value)
        return " ".join(text_chunks)

    if isinstance(content, dict):
        text_value = content.get("text")
        if isinstance(text_value, str):
            return text_value

    if hasattr(content, "text"):
        text_value = getattr(content, "text", None)
        if isinstance(text_value, str):
            return text_value

    return ""


def _extract_tool_calls(message: ChatCompletionRequestMessage | Any) -> list[Any]:
    tool_calls = getattr(message, "tool_calls", None)
    if tool_calls is None:
        return []

    if hasattr(tool_calls, "root"):
        tool_calls = tool_calls.root

    if isinstance(tool_calls, list):
        return tool_calls

    if isinstance(tool_calls, tuple):
        return list(tool_calls)

    if isinstance(tool_calls, dict):
        return [tool_calls]

    return []


def _should_use_empty_content_fallback(message: ChatCompletionRequestMessage, finish_reason: str | None) -> bool:
    if finish_reason in {"tool_calls", "function_call"}:
        return False

    if _extract_tool_calls(message):
        return False

    return _extract_message_text(message).strip() == ""


def _build_synthesized_response(
    response: CreateChatCompletionResponse,
    *,
    stop_reason: str,
    request_messages: list[ChatCompletionRequestMessage],
    intro_line: str,
) -> CreateChatCompletionResponse:
    """Build a final response by synthesizing gathered tool evidence.

    Shared by the empty-content and tool-loop-stop fallbacks, which differ only
    in their intro line. The body is identical: collect tool-message text,
    filter out empty/weak search fallbacks, summarize the informative remainder,
    and attach the result as the assistant's final content.
    """
    summary_parts: list[str] = [intro_line]

    if request_messages:
        tool_messages = [
            tool_text
            for message in request_messages
            if (tool_text := _extract_tool_message_text(message))
        ]

        if tool_messages:
            informative_messages = [
                message
                for message in tool_messages
                if message and not _looks_like_empty_search_fallback(message)
            ]
            if informative_messages:
                compact_summary = _summarize_tool_messages(informative_messages)
                summary_parts.append(_format_tool_synthesis(compact_summary, stop_reason, tool_messages))
            else:
                summary_parts.append(_format_weak_evidence_fallback(stop_reason))

    content = "\n\n".join(summary_parts)
    if content:
        content = content.strip()
    response.choices[0].message.content = content
    response.choices[0].message.tool_calls = None
    response.choices[0].finish_reason = _normalize_finish_reason("stop") or FinishReason1.stop
    return response


def _build_empty_content_response(
    response: CreateChatCompletionResponse,
    *,
    request_messages: list[ChatCompletionRequestMessage],
    stop_reason: str,
) -> CreateChatCompletionResponse:
    if stop_reason == "empty_response":
        intro_line = "The model returned an empty completion, so I synthesized the available tool evidence into a concise answer."
    else:
        intro_line = "The model returned an empty completion, so I synthesized the available context into a concise answer."
    return _build_synthesized_response(
        response,
        stop_reason=stop_reason,
        request_messages=request_messages,
        intro_line=intro_line,
    )


def _build_tool_loop_stop_response(
    response: CreateChatCompletionResponse,
    *,
    stop_reason: str,
    request_messages: list[ChatCompletionRequestMessage],
) -> CreateChatCompletionResponse:
    if stop_reason == "max_tool_turns":
        intro_line = "Note: The search or tool workflow reached its turn limit before finishing."
    elif stop_reason == "max_context_tokens":
        intro_line = "Note: The search or tool workflow stopped early because the conversation context grew too large."
    elif stop_reason == "repeated_tool_calls":
        intro_line = "Note: The tool workflow stopped because the same tool call was repeated without new information."
    elif stop_reason == "unfulfilled_action_stub":
        intro_line = "Note: A previous attempt announced an action but did not complete it or call any tool."
    else:
        intro_line = "Note: The workflow stopped before it could finish."
    return _build_synthesized_response(
        response,
        stop_reason=stop_reason,
        request_messages=request_messages,
        intro_line=intro_line,
    )


def _looks_like_empty_search_fallback(message: str) -> bool:
    lowered = message.lower()
    fallback_markers = (
        "no results were found",
        "bot detection",
        "try rephrasing your search",
        "try again in a few minutes",
        "returned no matches",
    )
    return any(marker in lowered for marker in fallback_markers)


def _has_tool_evidence(request_messages: list[ChatCompletionRequestMessage]) -> bool:
    """Return True if any tool message with usable text is present."""
    for message in request_messages:
        tool_text = _extract_tool_message_text(message)
        if tool_text and not _looks_like_empty_search_fallback(tool_text):
            return True
    return False


def _has_only_weak_tool_evidence(request_messages: list[ChatCompletionRequestMessage]) -> bool:
    tool_messages = []
    for message in request_messages:
        tool_text = _extract_tool_message_text(message)
        if tool_text:
            tool_messages.append(tool_text)

    if not tool_messages:
        return False

    informative_messages = [
        message
        for message in tool_messages
        if message and not _looks_like_empty_search_fallback(message)
    ]
    if informative_messages:
        return False

    return True


def _summarize_tool_messages(messages: list[str]) -> str:
    if not messages:
        return ""

    cleaned_messages = []
    for message in messages:
        cleaned = _clean_tool_message(message)
        if cleaned:
            cleaned_messages.append(cleaned)

    if not cleaned_messages:
        return ""

    if len(cleaned_messages) == 1:
        return _summarize_message_content(cleaned_messages[0])

    unique_messages = []
    seen: set[str] = set()
    for message in cleaned_messages:
        normalized = " ".join(message.split())
        if normalized in seen:
            continue
        seen.add(normalized)
        unique_messages.append(normalized)

    if len(unique_messages) == 1:
        return _summarize_message_content(unique_messages[0])

    filtered_messages = []
    for message in unique_messages:
        if _is_trivial_summary_fragment(message):
            continue
        filtered_messages.append(message)

    if not filtered_messages:
        return _summarize_message_content(unique_messages[0])

    if len(filtered_messages) == 1:
        return _summarize_message_content(filtered_messages[0])

    if len(filtered_messages) == 2:
        return _summarize_message_content(f"{filtered_messages[0]} Also, {filtered_messages[1]}")

    if len(filtered_messages) <= 3:
        return _summarize_message_content("; ".join(filtered_messages))

    return _summarize_message_content("; ".join(filtered_messages[:3]) + " …")


def _summarize_message_content(text: str, *, max_chars: int = 320) -> str:
    cleaned = " ".join(text.split())
    if not cleaned:
        return ""

    if "search results" in cleaned.lower():
        return _extract_search_result_titles(cleaned)

    if len(cleaned) <= max_chars:
        return cleaned

    return cleaned[: max_chars - 1].rstrip() + "…"


def _extract_search_result_titles(text: str, *, max_items: int = 3) -> str:
    normalized = " ".join(text.split())
    titles: list[str] = []
    seen_titles: set[str] = set()

    for match in re.finditer(r"(?<!\w)(\d+)\.\s+(.+?)(?=(?:\s+\d+\.\s+)|\s+URL:|\s+Summary:|$)", normalized):
        title = match.group(2).strip()
        title = re.sub(r"\s+URL:.*$", "", title)
        title = re.sub(r"\s+Summary:.*$", "", title)
        title = re.sub(r"\s{2,}", " ", title)
        title = title.strip(" -")
        if not title:
            continue
        normalized_title = " ".join(title.split())
        if normalized_title.lower() in seen_titles:
            continue
        seen_titles.add(normalized_title.lower())
        titles.append(normalized_title)
        if len(titles) >= max_items:
            break

    if titles:
        return "Top findings: " + "; ".join(titles)

    return _compact_text(text)


def _compact_text(text: str, *, max_chars: int = 320) -> str:
    cleaned = " ".join(text.split())
    if len(cleaned) <= max_chars:
        return cleaned

    return cleaned[: max_chars - 1].rstrip() + "…"


def _clean_tool_message(message: str) -> str:
    cleaned = " ".join(message.split())
    prefixes = (
        "result:",
        "results:",
        "note:",
        "summary:",
        "findings:",
    )
    lowered = cleaned.lower()
    for prefix in prefixes:
        if lowered.startswith(prefix):
            cleaned = cleaned[len(prefix):].strip()
            break

    if cleaned.startswith("{") and cleaned.endswith("}"):
        return "structured data returned by a tool"

    if "\n" in cleaned:
        lines = [line.strip() for line in cleaned.splitlines() if line.strip()]
        if len(lines) > 1:
            cleaned = "; ".join(lines[:3])

    return cleaned


def _is_trivial_summary_fragment(message: str) -> bool:
    lowered = message.lower().strip()
    trivial_phrases = (
        "the tool call result is empty",
        "the tool result is empty",
        "empty",
        "no additional details",
        "no further details",
    )
    return lowered in trivial_phrases or lowered.startswith("result:") or lowered.startswith("results:")


def _format_tool_synthesis(summary: str, stop_reason: str, tool_messages: list[str]) -> str:
    is_search_like = any(_looks_like_search_result(message) for message in tool_messages)
    if is_search_like:
        title = "Search results gathered"
        if stop_reason == "max_tool_turns":
            intro = "I found some search results, but the workflow reached its turn limit before I could fully synthesize them."
        else:
            intro = "I collected some search results before stopping."
    else:
        title = "Useful information gathered"
        if stop_reason == "max_tool_turns":
            intro = "I found several relevant leads, but the workflow reached its turn limit before I could fully synthesize them."
        else:
            intro = "I collected some information before stopping."

    bullets = [
        intro,
        "",
        f"**{title}**",
        "- " + summary.replace("\n", "\n- ") if summary else "- No additional details were gathered.",
    ]
    return "\n".join(bullets)


def _format_weak_evidence_fallback(stop_reason: str) -> str:
    if stop_reason == "max_tool_turns":
        return "**No reliable evidence gathered**\n\nI wasn't able to gather enough reliable evidence before the workflow reached its turn limit. A narrower or more specific query may produce better results."

    return "**No reliable evidence gathered**\n\nI wasn't able to gather enough reliable evidence before stopping. A narrower or more specific query may produce better results."


def _looks_like_search_result(message: str) -> bool:
    lowered = message.lower()
    search_markers = (
        "repository:",
        "search results",
        "result:",
        "results:",
        "repo",
        "github",
        "mcp server",
        "open source",
    )
    return any(marker in lowered for marker in search_markers)


_PSEUDO_TOOL_CALL_PATTERN = re.compile(
    r"<\|?(?:tool_call|function_call|function)[=>|_]|<invoke\b",
    re.IGNORECASE,
)


def _contains_pseudo_tool_call_markers(text: str) -> bool:
    """Return True if the model emitted tool calls as plain text instead of
    structured ``tool_calls``.

    Some reasoning models (e.g. Liquid LFM2.5) advertise ``tools`` support but do
    not emit OpenAI-style ``tool_calls``. They instead write markers such as
    ``<|tool_call_start|>``, ``<tool_call>``, ``<function=...>``, or Anthropic-style
    ``<invoke name="...">`` directly into the assistant ``content``. The bridge
    cannot execute these, so we detect and reject them.
    """
    if not text:
        return False
    return bool(_PSEUDO_TOOL_CALL_PATTERN.search(text))


# Matches an Anthropic-style tool invocation block:
#   <invoke name="tool_name">
#     <parameter name="arg_name">value</parameter>
#   </invoke>
_INVOKE_BLOCK_PATTERN = re.compile(
    r"<invoke\s+name=[\"']([^\"']+)[\"']>(.*?)</invoke>",
    re.IGNORECASE | re.DOTALL,
)
_PARAMETER_PATTERN = re.compile(
    r"<parameter\s+name=[\"']([^\"']+)[\"']>(.*?)</parameter>",
    re.IGNORECASE | re.DOTALL,
)

# Matches a <tool_call>...</tool_call> wrapper block (used for stripping).
_TOOL_CALL_BLOCK_PATTERN = re.compile(
    r"<tool_call>.*?</tool_call>",
    re.IGNORECASE | re.DOTALL,
)

# Matches a function-call block in the format some models emit:
#   <tool_call>
#     <function=fetch>
#       <parameter=max_length>3000</parameter>
#       <parameter=url>https://...</parameter>
#     </function>
#   </tool_call>
_FUNCTION_BLOCK_PATTERN = re.compile(
    r"<function=([^>]+)>(.*?)</function>",
    re.IGNORECASE | re.DOTALL,
)
_FUNCTION_PARAMETER_PATTERN = re.compile(
    r"<parameter=([^>]+)>(.*?)</parameter>",
    re.IGNORECASE | re.DOTALL,
)


def _coerce_pseudo_value(value: str) -> Any:
    """Interpret a pseudo tool-call parameter value as JSON when possible."""
    try:
        return json.loads(value)
    except (json.JSONDecodeError, ValueError):
        return value


def _parse_pseudo_tool_calls(text: str) -> list[tuple[str, str]]:
    """Parse pseudo tool-call markers from plain text into
    ``(tool_name, arguments_json)`` tuples.

    Supports two common formats:
    * Anthropic-style ``<invoke name="..."><parameter name="...">...</parameter></invoke>``
    * ``<tool_call><function=NAME><parameter=ARG>value</parameter></function></tool_call>``

    Returns an empty list if no parseable invocations are found.
    """
    if not text:
        return []

    calls: list[tuple[str, str]] = []

    # Format 1: <invoke name="...">...</invoke>
    for match in _INVOKE_BLOCK_PATTERN.finditer(text):
        tool_name = match.group(1).strip()
        body = match.group(2)
        if not tool_name:
            continue

        arguments: dict[str, Any] = {}
        for param in _PARAMETER_PATTERN.finditer(body):
            arg_name = param.group(1).strip()
            arg_value = param.group(2).strip()
            if not arg_name:
                continue
            arguments[arg_name] = _coerce_pseudo_value(arg_value)

        calls.append((tool_name, json.dumps(arguments)))

    # Format 2: <function=NAME>...</function>
    for match in _FUNCTION_BLOCK_PATTERN.finditer(text):
        tool_name = match.group(1).strip()
        body = match.group(2)
        if not tool_name:
            continue

        arguments: dict[str, Any] = {}
        for param in _FUNCTION_PARAMETER_PATTERN.finditer(body):
            arg_name = param.group(1).strip()
            arg_value = param.group(2).strip()
            if not arg_name:
                continue
            arguments[arg_name] = _coerce_pseudo_value(arg_value)

        calls.append((tool_name, json.dumps(arguments)))

    return calls


def _build_synthetic_tool_calls(
    parsed_calls: list[tuple[str, str]],
) -> list[Any]:
    """Build synthetic OpenAI-style tool_call objects from parsed pseudo calls.

    Each returned object has ``id``, ``type``, and ``function`` (with ``name``
    and ``arguments``) attributes, matching the shape the tool loop expects.

    The ``id`` uses the OpenAI ``call_<uuid>`` format because some providers
    (e.g. minimax) reject non-standard IDs like ``pseudo-call-0`` with
    "tool call id is invalid".
    """
    import uuid
    from types import SimpleNamespace

    tool_calls: list[Any] = []
    for name, arguments_json in parsed_calls:
        tool_calls.append(
            SimpleNamespace(
                id=f"call_{uuid.uuid4().hex}",
                type="function",
                function=SimpleNamespace(
                    name=name,
                    arguments=arguments_json,
                ),
            )
        )
    return tool_calls


def _strip_pseudo_tool_call_markers(text: str) -> str:
    """Remove pseudo tool-call marker blocks from assistant content.

    When a model emits tool calls as plain-text markers (e.g.
    ``<tool_call><function=NAME>...</function></tool_call>`` or
    ``<invoke name="...">...</invoke>``), the bridge parses them into real
    tool calls. The raw markers must then be stripped from the assistant
    content so they don't leak into the conversation and the final response.
    """
    if not text:
        return text

    # Remove <tool_call>...</tool_call> blocks (and any <function=...> inside).
    stripped = _TOOL_CALL_BLOCK_PATTERN.sub("", text)
    # Remove <invoke name="...">...</invoke> blocks.
    stripped = _INVOKE_BLOCK_PATTERN.sub("", stripped)
    # Remove any leftover <dots_function_call> / <dots_function_call> wrappers.
    stripped = re.sub(r"</?dots_function_call>", "", stripped, flags=re.IGNORECASE)
    # Collapse leftover blank lines.
    stripped = re.sub(r"\n{3,}", "\n\n", stripped)
    return stripped.strip()


# Matches an assistant reply that announces intent to perform an action (e.g.
# "Let me fetch...", "I'll search...", "I need to check...") at the very start
# of the content.
_INTENT_STUB_PATTERN = re.compile(
    r"^(?:let(?:'s|s)?(?:\s+me)?|let\s+us|i(?:'ll|'m going to| will| need to| am going to| plan to| should)|"
    r"allow\s+me\s+to|going\s+to|i\s+shall)\b[^.!?\n]{0,80}?\b"
    r"(?:fetch|search|check|look\s*up|browse|retrieve|find|verify|confirm|review|read|open|"
    r"query|investigate|research|examine|consult|access|visit|call|use|pull\s+up|dig\s+into)\b",
    re.IGNORECASE,
)


def _looks_like_unfulfilled_action_stub(text: str, *, max_words: int = 30, max_sentences: int = 2) -> bool:
    """Return True if `text` is a "throat-clearing" stub: the assistant announces
    an action it is about to take (fetch/search/check/...) but the message has
    no attached tool call and no further substantive content — i.e. the real
    work (a tool invocation, or an actual answer) never happened.

    This is distinct from an empty completion (``_should_use_empty_content_fallback``)
    or plain-text pseudo tool-call markers (``_contains_pseudo_tool_call_markers``):
    the content here is well-formed, non-empty prose, so naive
    "content is non-empty" checks (as used by CLI pipelines that only assert
    ``choices[0].message.content`` is a non-empty string) accept it as a valid
    final answer. In practice this shows up when an upstream provider (e.g. a
    ``:free`` tier model under load) cuts a generation off right after this kind
    of preamble but still reports ``finish_reason: "stop"``.

    Both a low word/sentence count AND the leading intent phrase are required,
    so a genuinely long answer that merely opens with "Let me summarize..."
    is never flagged.
    """
    stripped = text.strip()
    if not stripped or not _INTENT_STUB_PATTERN.match(stripped):
        return False

    if len(stripped.split()) > max_words:
        return False

    sentence_count = len([s for s in re.split(r"(?<=[.!?])\s+", stripped) if s.strip()])
    return sentence_count <= max_sentences


# Sentinel returned by ``_handle_stub_or_stop`` to tell the caller to drop the
# just-appended stub assistant message and retry the upstream call, rather than
# returning a value directly (the retry itself must happen in the caller's
# ``while`` loop via ``continue``).
_RETRY_TOOL_LOOP = object()


async def _handle_stub_or_stop(
    client: Any,
    request: CreateChatCompletionRequest,
    *,
    assistant_text: str,
    response: CreateChatCompletionResponse,
    stub_retry_count: int,
    max_stub_retries: int,
) -> Any:
    """Decide what to do when the model produced no usable tool call.

    Returns ``_RETRY_TOOL_LOOP`` if ``assistant_text`` looks like an unfulfilled
    action-intent stub (e.g. "Let me fetch the page...") and retries remain --
    the caller should pop the stub message it just appended and retry the
    upstream call. Otherwise returns a ``CreateChatCompletionResponse`` for the
    caller to return as-is: either the original ``response`` (not a stub), or a
    synthesized final answer (a stub that has exhausted its retries).
    """
    if not _looks_like_unfulfilled_action_stub(assistant_text):
        logger.debug("no tool calls found")
        return response

    if stub_retry_count < max_stub_retries:
        logger.warning(
            "model returned an unfulfilled action-intent stub "
            f"('{assistant_text[:80]}') with no tool calls; "
            f"retrying upstream request ({stub_retry_count + 1}/{max_stub_retries})"
        )
        return _RETRY_TOOL_LOOP

    logger.warning(
        "model repeatedly returned an unfulfilled action-intent stub "
        f"('{assistant_text[:80]}'); synthesizing a final answer instead"
    )
    synthesized_response = await _try_synthesize_tool_loop_result(
        client,
        request,
        stop_reason="unfulfilled_action_stub",
        request_messages=request.messages,
    )
    if synthesized_response is not None:
        return synthesized_response
    return _build_tool_loop_stop_response(
        response,
        stop_reason="unfulfilled_action_stub",
        request_messages=request.messages,
    )


def _is_transient_upstream_error(text: str) -> bool:
    """Return True if the upstream body indicates a transient provider error.

    Free-tier providers sometimes return HTTP 200 with an error body like
    ``{"error": {"message": "Upstream provider error", "code": 502}}`` or a
    5xx "overloaded"/"unavailable" message. These are transient and worth a
    short retry rather than failing the whole run.
    """
    if not text:
        return False
    lowered = text.lower()
    transient_markers = (
        "overloaded",
        "unavailable",
        "upstream provider error",
        "provider returned error",
        "temporarily",
        "try again later",
        "rate limit",
        "too many requests",
        "internal server error",
        "bad gateway",
        "service unavailable",
    )
    return any(marker in lowered for marker in transient_markers)


def _is_retryable_upstream_status(status_code: int, text: str) -> bool:
    """Return True if an upstream response is worth retrying.

    Retryable: 5xx, 429 (rate limit), or HTTP 200 with a transient error body.
    A 429 is explicitly retryable because free-tier providers rate-limit under
    sustained load (e.g. a long research loop) and the response usually carries
    a ``Retry-After`` hint telling us how long to wait.
    """
    if status_code == 429:
        return True
    if status_code >= 500:
        return True
    if status_code == 200 and _is_transient_upstream_error(text):
        return True
    return False


def _get_retry_after_seconds(response: Any) -> float:
    """Extract the provider's ``Retry-After`` hint (seconds) from a response.

    Checks the ``Retry-After`` HTTP header first, then the ``retry_after_seconds``
    field in the JSON error body (OpenRouter/OpenAI-style). Returns 0.0 if no
    hint is present. The value is capped at ``MAX_UPSTREAM_RETRY_AFTER_SECONDS``
    so a single request cannot stall a worker for an unreasonable time.
    """
    try:
        header = response.headers.get("Retry-After")
        if header:
            value = float(header)
            return min(max(value, 0.0), MAX_UPSTREAM_RETRY_AFTER_SECONDS)
    except (AttributeError, TypeError, ValueError):
        pass

    try:
        payload = json.loads(response.text)
        seconds = (
            payload.get("error", {}).get("metadata", {}).get("retry_after_seconds")
        )
        if seconds is not None:
            value = float(seconds)
            return min(max(value, 0.0), MAX_UPSTREAM_RETRY_AFTER_SECONDS)
    except (AttributeError, TypeError, ValueError, json.JSONDecodeError):
        pass

    return 0.0


async def chat_completions(
    request: CreateChatCompletionRequest,
    http_request: Request,
    trace_logger: RequestTraceLogger | None = None,
) -> CreateChatCompletionResponse:
    """performs a chat completion using the inference server"""

    if not getattr(request, "tools", None):
        request = await chat_completion_add_tools(request)
    if trace_logger is not None:
        trace_logger.record("tools_discovered", tools=[tool.model_dump(exclude_defaults=True, exclude_none=True, exclude_unset=True) for tool in request.tools])

    max_tool_turns = get_max_tool_turns()
    max_stub_retries = get_max_stub_retries()
    tool_timeout_seconds = get_tool_timeout_seconds()
    tool_turns_completed = 0
    stub_retry_count = 0
    tool_client_cache: dict[str, Any] = {}
    seen_tool_calls: dict[str, int] = {}
    tool_result_cache = ToolResultCache()
    persistent_tool_cache = get_tool_cache()

    # Per-server opt-in caching: only tools whose owning MCP server is
    # configured with `"cached": true` are read from / written to the caches.
    # The tool->server map is attached during tool discovery.
    tool_server_map: dict[str, str] = getattr(request, "_tool_server_map", {}) or {}
    cached_servers: set[str] = getattr(config, "cached_mcp_servers", set()) or set()

    def _cache_enabled(tool_name: str) -> bool:
        server = tool_server_map.get(tool_name)
        return server is not None and server in cached_servers

    async with get_client(http_request) as client:
        while True:
            start_time = time.perf_counter()
            # logger.debug(request.model_dump_json())
            upstream_response = await client.post(
                "/chat/completions",
                #content=request.model_dump_json(
                #    exclude_defaults=True, exclude_none=True, exclude_unset=True
                #),
                json=request.model_dump(exclude_defaults=True, exclude_none=True, exclude_unset=True),
            )
            text = upstream_response.text
            logger.debug(f"upstream chat completion response received: status={upstream_response.status_code}")
            _record_timing(trace_logger, "upstream_llm_request", time.perf_counter() - start_time)

            # Retry transient provider errors (5xx, 429 rate-limit, or HTTP 200
            # with an error body like "overloaded"/"provider returned error").
            # Free-tier providers are flaky under load; a short retry avoids
            # failing a strong model's run on a transient blip. When the
            # provider supplies a `Retry-After` hint (common for 429), honor it
            # so the provider has time to recover instead of us hammering it.
            if _is_retryable_upstream_status(upstream_response.status_code, text):
                retried = False
                for attempt in range(DEFAULT_UPSTREAM_RETRY_COUNT):
                    retry_after = _get_retry_after_seconds(upstream_response)
                    delay = retry_after if retry_after > 0 else DEFAULT_UPSTREAM_RETRY_DELAY_SECONDS
                    logger.warning(
                        f"upstream transient error (status={upstream_response.status_code}); "
                        f"retrying ({attempt + 1}/{DEFAULT_UPSTREAM_RETRY_COUNT}) "
                        f"in {delay:.1f}s"
                    )
                    await asyncio.sleep(delay)
                    upstream_response = await client.post(
                        "/chat/completions",
                        json=request.model_dump(exclude_defaults=True, exclude_none=True, exclude_unset=True),
                    )
                    text = upstream_response.text
                    if not _is_retryable_upstream_status(upstream_response.status_code, text):
                        retried = True
                        break
                if not retried:
                    logger.error(f"upstream inference server returned status {upstream_response.status_code}: {text[:2000]}")
                    # If we already gathered tool evidence (e.g. after 30+ min of
                    # research), don't throw it all away on a final provider
                    # blip. Synthesize a fallback answer from the evidence we
                    # have instead of failing the whole run.
                    if _has_tool_evidence(request.messages):
                        logger.warning(
                            "upstream failed after tool evidence was gathered; "
                            "synthesizing a fallback answer from the evidence"
                        )
                        synthesized = await _try_synthesize_tool_loop_result(
                            client,
                            request,
                            stop_reason="max_tool_turns",
                            request_messages=request.messages,
                        )
                        if synthesized is not None:
                            return synthesized
                        # The upstream failed this turn, so there is no valid
                        # parsed `response` to base the fallback on. Build a
                        # synthetic one; `_build_tool_loop_stop_response` only
                        # overwrites `choices[0]` fields, so the base must be
                        # a *valid* `CreateChatCompletionResponse` (all required
                        # fields present) or `model_validate` raises before the
                        # fallback can run.
                        return _build_tool_loop_stop_response(
                            CreateChatCompletionResponse.model_validate(
                                {
                                    "id": "chatcmpl-fallback",
                                    "object": "chat.completion",
                                    "created": int(time.time()),
                                    "model": getattr(request, "model", "") or "unknown",
                                    "choices": [
                                        {
                                            "index": 0,
                                            "finish_reason": "stop",
                                            "message": {"role": "assistant", "content": ""},
                                        }
                                    ],
                                }
                            ),
                            stop_reason="max_tool_turns",
                            request_messages=request.messages,
                        )
                    raise HTTPException(
                        status_code=502,
                        detail=f"Upstream inference server returned status {upstream_response.status_code}",
                    )

            if upstream_response.status_code >= 400:
                logger.error(f"upstream inference server returned status {upstream_response.status_code}: {text[:2000]}")
                raise HTTPException(
                    status_code=502,
                    detail=f"Upstream inference server returned status {upstream_response.status_code}",
                )

            try:
                response = CreateChatCompletionResponse.model_validate_json(text)
                if trace_logger is not None:
                    trace_logger.record(
                        "llm_response",
                        response=response.model_dump(exclude_defaults=True, exclude_none=True, exclude_unset=True),
                    )

                if logger.level("DEBUG").name == "DEBUG":
                    response_preview = response.model_dump(exclude_defaults=True, exclude_none=True, exclude_unset=True)
                    compact_preview = json.dumps(response_preview, ensure_ascii=False)[:4000]
                    logger.debug(f"upstream response preview: {compact_preview}")
                    if response.choices:
                        message = response.choices[0].message
                        logger.debug(
                            "upstream message summary: "
                            f"role={getattr(getattr(message, 'root', message), 'role', None)}; "
                            f"content_len={len(_extract_message_text(message))}; "
                            f"tool_call_count={len(_extract_tool_calls(message))}; "
                            f"finish_reason={getattr(response.choices[0].finish_reason, 'value', None)}"
                        )
            except HTTPException:
                raise
            except Exception as e:
                # Log the raw upstream body so a parse failure is diagnosable.
                # Providers sometimes return a small error/empty body (e.g. a
                # 62-byte `{"error": ...}` or a truncated response) that is not
                # a valid chat completion; without the raw text we cannot tell
                # whether it was a transient blip, a rate limit, or a provider
                # bug.
                logger.error("error parsing upstream chat completion response")
                logger.error(f"upstream status={upstream_response.status_code}; raw body: {text[:2000]}")
                logger.error(e)
                raise HTTPException(
                    status_code=502,
                    detail="Failed to parse upstream chat completion response",
                ) from e

            if not response.choices:
                logger.error("upstream chat completion response contained no choices")
                raise HTTPException(
                    status_code=502,
                    detail="Upstream chat completion response contained no choices",
                )

            msg = response.choices[0].message
            if _should_use_empty_content_fallback(msg, finish_reason_value := response.choices[0].finish_reason.value if response.choices[0].finish_reason is not None else None):
                logger.warning("upstream model returned empty assistant content without tool calls; synthesizing a fallback response from tool evidence")
                return _build_empty_content_response(
                    response,
                    request_messages=request.messages,
                    stop_reason="empty_response",
                )

            msg = ChatCompletionRequestMessage(
                role="assistant",
                content=msg.content,
                tool_calls=msg.tool_calls,
            )  # type: ignore
            request.messages.append(msg)

            finish_reason_label = response.choices[0].finish_reason.value if response.choices[0].finish_reason is not None else None
            logger.debug(
                "chat completion finish reason: "
                f"{finish_reason_label}; tool_calls={bool(getattr(response.choices[0].message, 'tool_calls', None))}"
            )
            if trace_logger is not None:
                trace_logger.record(
                    "assistant_message",
                    message=msg.model_dump(exclude_defaults=True, exclude_none=True, exclude_unset=True),
                )

            finish_reason_value = (
                response.choices[0].finish_reason.value
                if response.choices[0].finish_reason is not None
                else None
            )
            if finish_reason_value in ["stop", "length"]:
                assistant_text = _extract_message_text(msg)
                if _contains_pseudo_tool_call_markers(assistant_text):
                    # The model emitted Anthropic-style tool-call markers as
                    # plain text instead of structured tool_calls. Parse them
                    # into real tool calls and execute them, rather than
                    # failing the request.
                    parsed_calls = _parse_pseudo_tool_calls(assistant_text)
                    if parsed_calls:
                        logger.warning(
                            f"model emitted pseudo tool-call markers as plain text; "
                            f"parsing {len(parsed_calls)} tool call(s) for execution"
                        )
                        synthetic_calls = _build_synthetic_tool_calls(parsed_calls)
                        msg.tool_calls = synthetic_calls
                        # The tool loop reads tool_calls from
                        # response.choices[0].message, so mirror them there too.
                        response.choices[0].message.tool_calls = synthetic_calls
                        # Strip the raw markers from the assistant content so
                        # they don't leak into the conversation / final response.
                        cleaned_content = _strip_pseudo_tool_call_markers(assistant_text)
                        if cleaned_content:
                            msg.content = cleaned_content
                            response.choices[0].message.content = cleaned_content
                        if trace_logger is not None:
                            trace_logger.record(
                                "pseudo_tool_calls_parsed",
                                tool_calls=[{"name": name, "arguments": arguments} for name, arguments in parsed_calls],
                            )
                        # Fall through to the normal tool-call execution path.
                    else:
                        logger.warning(
                            "model emitted pseudo tool-call markers as plain text "
                            "(e.g. <|tool_call_start|> / <tool_call> / <function=...>); "
                            "model does not support structured tool calls via the bridge"
                        )
                        raise HTTPException(
                            status_code=502,
                            detail=(
                                "The model does not support structured tool calls and "
                                "emitted tool-call markers as plain text. Use a model "
                                "with native tool-call support."
                            ),
                        )
                else:
                    stub_result = await _handle_stub_or_stop(
                        client,
                        request,
                        assistant_text=assistant_text,
                        response=response,
                        stub_retry_count=stub_retry_count,
                        max_stub_retries=max_stub_retries,
                    )
                    if stub_result is _RETRY_TOOL_LOOP:
                        stub_retry_count += 1
                        request.messages.pop()
                        continue
                    return stub_result

            logger.debug("tool calls found")
            if trace_logger is not None:
                trace_logger.record("tool_call_decision", finish_reason=finish_reason_value)
            tool_call_items = []
            for tool_call in _extract_tool_calls(response.choices[0].message):
                function = getattr(tool_call, "function", None)
                if isinstance(function, dict):
                    name = function.get("name")
                    arguments = function.get("arguments")
                else:
                    name = getattr(function, "name", None)
                    arguments = getattr(function, "arguments", None)

                if name is None:
                    continue

                tool_call_items.append((name, arguments))

            if not tool_call_items:
                # The model may have advertised a tool_calls finish reason but
                # emitted Anthropic-style pseudo markers as plain text content
                # with no structured tool_calls. Parse them so the tools still
                # execute instead of returning the raw markers.
                assistant_text = _extract_message_text(msg)
                if _contains_pseudo_tool_call_markers(assistant_text):
                    parsed_calls = _parse_pseudo_tool_calls(assistant_text)
                    if parsed_calls:
                        logger.warning(
                            f"model returned tool_calls finish reason with pseudo markers; "
                            f"parsing {len(parsed_calls)} tool call(s) for execution"
                        )
                        synthetic_calls = _build_synthetic_tool_calls(parsed_calls)
                        msg.tool_calls = synthetic_calls
                        response.choices[0].message.tool_calls = synthetic_calls
                        # Strip the raw markers from the assistant content so
                        # they don't leak into the conversation / final response.
                        cleaned_content = _strip_pseudo_tool_call_markers(assistant_text)
                        if cleaned_content:
                            msg.content = cleaned_content
                            response.choices[0].message.content = cleaned_content
                        if trace_logger is not None:
                            trace_logger.record(
                                "pseudo_tool_calls_parsed",
                                tool_calls=[{"name": name, "arguments": arguments} for name, arguments in parsed_calls],
                            )
                        tool_call_items = [(name, arguments) for name, arguments in parsed_calls]
                    else:
                        stub_result = await _handle_stub_or_stop(
                            client,
                            request,
                            assistant_text=assistant_text,
                            response=response,
                            stub_retry_count=stub_retry_count,
                            max_stub_retries=max_stub_retries,
                        )
                        if stub_result is _RETRY_TOOL_LOOP:
                            stub_retry_count += 1
                            request.messages.pop()
                            continue
                        return stub_result
                else:
                    stub_result = await _handle_stub_or_stop(
                        client,
                        request,
                        assistant_text=assistant_text,
                        response=response,
                        stub_retry_count=stub_retry_count,
                        max_stub_retries=max_stub_retries,
                    )
                    if stub_result is _RETRY_TOOL_LOOP:
                        stub_retry_count += 1
                        request.messages.pop()
                        continue
                    return stub_result

            # Detect a "search loop": the model re-issuing the same tool call
            # across iterations without converging. Stop early and synthesize a
            # final answer from the tool evidence already gathered.
            #
            # We first try the model itself to synthesize (a capable model can
            # produce a real answer from the gathered evidence). Only if that
            # fails or returns empty do we fall back to the deterministic
            # evidence summary. This keeps strong models producing real answers
            # while still degrading gracefully for weak models that would just
            # echo the tool-call arguments back.
            if tool_call_items and _detect_repeated_tool_calls(tool_call_items, seen_tool_calls):
                logger.warning(
                    "detected repeated tool call(s); stopping tool loop and synthesizing a final answer"
                )
                synthesized_response = await _try_synthesize_tool_loop_result(
                    client,
                    request,
                    stop_reason="repeated_tool_calls",
                    request_messages=request.messages,
                )
                if synthesized_response is not None:
                    return synthesized_response
                return _build_tool_loop_stop_response(
                    response,
                    stop_reason="repeated_tool_calls",
                    request_messages=request.messages,
                )

            if not should_continue_tool_loop(
                finish_reason_value,
                tool_call_count=len(tool_call_items),
                iteration_count=tool_turns_completed,
                max_tool_turns=max_tool_turns,
            ):
                logger.warning(
                    _format_tool_loop_stop_message(
                        tool_turns_completed=tool_turns_completed,
                        max_tool_turns=max_tool_turns,
                    )
                )
                synthesized_response = await _try_synthesize_tool_loop_result(
                    client,
                    request,
                    stop_reason="max_tool_turns",
                    request_messages=request.messages,
                )
                if synthesized_response is not None:
                    return synthesized_response
                return _build_tool_loop_stop_response(
                    response,
                    stop_reason="max_tool_turns",
                    request_messages=request.messages,
                )

            if _has_only_weak_tool_evidence(request.messages):
                logger.warning("tool evidence is weak or empty; stopping tool loop before another iteration")
                synthesized_response = await _try_synthesize_tool_loop_result(
                    client,
                    request,
                    stop_reason="max_tool_turns",
                    request_messages=request.messages,
                )
                if synthesized_response is not None:
                    return synthesized_response
                return _build_tool_loop_stop_response(
                    response,
                    stop_reason="max_tool_turns",
                    request_messages=request.messages,
                )

            max_context_tokens = get_max_context_tokens(getattr(request, "model", None))
            if _context_budget_exceeded(response, max_context_tokens):
                prompt_tokens = getattr(getattr(response, "usage", None), "prompt_tokens", None)
                logger.warning(
                    f"tool loop context budget exceeded ({prompt_tokens} > {max_context_tokens} tokens); "
                    "stopping tool loop and synthesizing a final answer"
                )
                synthesized_response = await _try_synthesize_tool_loop_result(
                    client,
                    request,
                    stop_reason="max_context_tokens",
                    request_messages=request.messages,
                )
                if synthesized_response is not None:
                    return synthesized_response
                return _build_tool_loop_stop_response(
                    response,
                    stop_reason="max_context_tokens",
                    request_messages=request.messages,
                )

            # Proactive context compression: if the budget is nearly exceeded,
            # compress older tool messages into a summary so the loop can keep
            # going instead of stopping early.
            if _context_budget_nearly_exceeded(response, max_context_tokens):
                if _compress_tool_context(request.messages):
                    logger.info(
                        "context budget nearly exceeded; compressed older tool messages; "
                        "continuing tool loop"
                    )
                    continue

            tool_turns_completed += 1

            if tool_call_items:
                tool_call_results = await call_tools(
                    tool_call_items,
                    timeout=tool_timeout_seconds,
                    trace_logger=trace_logger,
                    client_cache=tool_client_cache,
                    result_cache=tool_result_cache,
                    persistent_cache=persistent_tool_cache,
                    cache_enabled=_cache_enabled,
                )
                if trace_logger is not None:
                    trace_logger.record("mcp_tool_calls", tool_calls=[{"name": name, "arguments": arguments} for name, arguments in tool_call_items])

                tool_errors: list[str] = []
                tool_call_messages = _extract_tool_calls(response.choices[0].message)
                for tool_call, tool_call_result in zip(
                    tool_call_messages,
                    tool_call_results,
                ):
                    function = getattr(tool_call, "function", None)
                    if isinstance(function, dict):
                        tool_name = function.get("name", "unknown")
                    else:
                        tool_name = getattr(function, "name", "unknown")

                    if tool_call_result is None:
                        logger.warning(
                            f"tool call '{tool_name}' returned no result"
                        )
                        continue

                    logger.debug(
                        "tool call completed: "
                        f"name={tool_name}; "
                        f"parts={len(getattr(tool_call_result, 'content', []) or [])}; "
                        f"isError={getattr(tool_call_result, 'isError', False)}"
                    )
                    if trace_logger is not None:
                        trace_logger.record(
                            "mcp_tool_result",
                            tool_name=tool_name,
                            result=tool_call_result.model_dump(exclude_defaults=True, exclude_none=True, exclude_unset=True),
                        )

                    if getattr(tool_call_result, "content", None):
                        preview_text = str(tool_call_result.content)
                        preview_text = " ".join(preview_text.split())
                        if len(preview_text) > 400:
                            preview_text = preview_text[:397].rstrip() + "…"
                        logger.debug(
                            "tool call result content preview: "
                            f"{preview_text}"
                        )

                    if getattr(tool_call_result, "isError", False):
                        error_text = next(
                            (
                                part.text
                                for part in getattr(tool_call_result, "content", [])
                                if getattr(part, "type", None) == "text"
                            ),
                            "tool call failed",
                        )
                        tool_errors.append(f"{tool_name}: {error_text}")

                    tools_content = sanitize_tool_result_content(
                        tool_name,
                        tool_call_result,
                    )
                    request.messages.append(
                        ChatCompletionRequestMessage.model_validate(
                            {
                                "role": "tool",
                                "content": tools_content,
                                "tool_call_id": getattr(tool_call, "id", None) if not isinstance(tool_call, dict) else tool_call.get("id"),
                            }
                        )
                    )

                    if trace_logger is not None:
                        trace_logger.record(
                            "tool_message",
                            tool_name=tool_call.function.name,
                            tool_result=tool_call_result.model_dump(exclude_defaults=True, exclude_none=True, exclude_unset=True),
                        )

                    logger.debug("sending next iteration of chat completion request")

                if tool_errors:
                    should_stop = _should_stop_tool_loop_on_tool_errors(tool_errors, request.messages)
                    if should_stop:
                        logger.warning(
                            f"tool call failures detected; stopping tool loop: {'; '.join(tool_errors)}"
                        )
                        return _build_tool_error_response(response, tool_errors)

                    # Recoverable failures (e.g. a validation error on one tool
                    # call). The error messages were already appended to
                    # request.messages above, so continuing the loop lets the
                    # LLM see exactly what went wrong and correct its arguments
                    # on the next iteration. The loop is still bounded by
                    # max_tool_turns via should_continue_tool_loop.
                    logger.warning(
                        f"tool call failures detected; feeding errors back to the model for correction: {'; '.join(tool_errors)}"
                    )
                    continue
